---
# T창che pour inclure les t창ches principale de l'installation du Cluster

- name: Inclure la t창che de configuration commune aux VM
  import_tasks: kibana_commun.yml
  ignore_errors: true

- name: Include la t창che d'installation du Kibana
  import_tasks: kibana_install.yml
  ignore_errors: true

# Fin