---
# T창che pour inclure les t창ches principale de l'installation du Cluster

- name: Inclure la t창che de configuration commune aux VM
  import_tasks: logstash_commun.yml
  ignore_errors: true

- name: Include la t창che d'installation de Logstash
  import_tasks: logstash_install.yml
  ignore_errors: true

# Fin
